# Generated by Django 5.1.5 on 2025-01-23 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto', models.CharField(max_length=10)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('fecha_compra', models.DateField()),
                ('numero_factura', models.CharField(max_length=20)),
            ],
        ),
    ]
